# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
