# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170213_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_schedule',
        ),
    ]
