# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170213_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_next_report_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_next_report_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_schedule',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_schedule',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_schedule',
            field=models.IntegerField(default=7),
        ),
    ]
