# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170213_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_reports_allowed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='daily_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monthly_schedule',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_reports_allowed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_schedule',
        ),
        migrations.AddField(
            model_name='profile',
            name='schedule_interval',
            field=models.IntegerField(default=1),
        ),
    ]
