# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170213_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='schedule_interval',
            new_name='schedule',
        ),
    ]
