# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170213_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='schedule',
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_reports_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_reports_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
