# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170213_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daily_schedule',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_schedule',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weekly_schedule',
            field=models.IntegerField(null=True),
        ),
    ]
