# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20170214_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='daily_reports_allowed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='weekly_reports_allowed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='reports_allowed',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
