# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20170213_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
