# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170214_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
