# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-14 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_check_nag'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag',
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
