# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20170214_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='nag',
            new_name='nag_interval',
        ),
    ]
